# NumPy

In [1]:
import numpy as np

# The Basics

In [33]:
a= np.array([1,2,3],dtype="int32")
print(a)

[1 2 3]


In [34]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [35]:
#Get dimension
a.ndim

1

In [36]:
#Get Shape
#a.shape
b.shape

(2, 3)

In [37]:
#Get Type
a.dtype

dtype('int32')

In [44]:
#Get Size
a.itemsize
#b.itemsize

4

In [45]:
#Get total size
#a.size * a.itemsize
a.nbytes

#b.nbytes

12

# Accessing/Changing specific elements,rows,columns etc.,

In [47]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [51]:
#get a specific element[r,c]
a[0,6]
#a[1,-2]

7

In [52]:
#get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [53]:
#get a specific column
a[:, 2]

array([ 3, 10])

In [56]:
#Getting a little more fancy  [startindex:endindex:stepsize]
a[0, 1:6:2]
a[0, 1:-1:2]


array([2, 4, 6])

In [59]:
a[1,5]=20
print(a)

a[: ,2]=[1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
#3-d example

In [60]:
b=np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [63]:
#Get specific element (work outside in )
b[0,1,1]


4

In [66]:
#replace
b[:,1,:]

array([[3, 4]])

# Intializing Different Types  of Arrays

In [70]:
#ALL 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
#ALL 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [72]:
#Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [76]:
#any other Number (full_like)
np.full_like(a,4)
#np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [79]:
#Random decimal numbers
np.random.rand(4,2)
#np.random.rand(4,2,3)

array([[0.3150022 , 0.01889185],
       [0.44442512, 0.00934304],
       [0.90509106, 0.37432491],
       [0.32318814, 0.95510622]])

In [82]:
#Random Integer variables
np.random.randint(4,8, size=(3,3))

array([[7, 5, 4],
       [7, 4, 4],
       [4, 7, 4]])

In [84]:
#The identity matriz
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
#Repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
output =  np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful when copying arrays!!!!!!

In [100]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [111]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [112]:

a+2

array([3, 4, 5, 6])

In [103]:
a-2

array([-1,  0,  1,  2])

In [104]:
a*2

array([2, 4, 6, 8])

In [105]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [114]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [115]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [118]:
#Take the sin
#np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [121]:
a=np.ones((2,3))
print(a)

b=np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [122]:
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [125]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
np.min(stats)

1

In [127]:
np.max(stats,axis=1)

array([3, 6])

In [128]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing arrays

In [131]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.shape((4,2))

[[1 2 3 4]
 [5 6 7 8]]


TypeError: 'tuple' object is not callable

In [132]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [134]:
#horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellanous

Load Data from File

In [136]:
np.genfromtxt('data.txt',delimeters=',')

TypeError: genfromtxt() got an unexpected keyword argument 'delimeters'